### ISSUE TITLE
Script doesn't exit 

### ISSUE THREAD

**Issue by adrianchmura1** [shibapm/Komondor#12]
Hey,

Nice tool! I succesfully set up some useful hooks using it ;)

I tried to set up pre commit hook to run `swiftlint` which I got installed globally:

```
"pre-commit": [ "swiftlint" ]
```

The problem is the hook doesn't exit when project has a lot of warnings. When I modify swiftlint to execute it against a single file (which has less number of warnings) it exits normally. Swiftlint is working correctly when running directly from terminal. It is likely caused by `shellOut` in `runner.swift` script

**Comment by nicholascross** [comment]
Would running “swiftlint —strict” help?

This should cause it to fail on warnings.

**Comment by adrianchmura1** [comment]
Yeah it works that way. 
But I'd prefer that script just prints out warnings instead of failing. I'm afraid hooks are going to freeze if any script produce huge number of logs
