### ISSUE TITLE
Document commit integration in README directly

### ISSUE THREAD

**Issue by Dschee** [shibapm/Komondor#18]
I just wanted to test this out, but after reading the README I wasn't sure at first how commit hooks would get setup in my project since the `swift run komondor install` method was only documented within the "Getting Set Up" documents, but I personally think it's the key command and should be explained right within the README.

**Comment by orta** [comment]
Sure, happy to accept a PR 👍

**Comment by Dschee** [comment]
I would happily post a PR, but first to understand it correctly: In the SwiftPM "Getting Set Up" there is no mentions of the `swift run komondor install` command, is it even needed in that case?

**Comment by orta** [comment]
Yep, should be - likely is an oversight

**Comment by Dschee** [comment]
Ah, no, the `swift run komondor install` command is already mentioned in the README. So this might not have been an issue in the end. Must have overseen it. Closing.
