### ISSUE TITLE
Add support for macros

### ISSUE THREAD

**Issue by orta** [shibapm/Komondor#6]
`[edited]` could represent all the files changed, so you could run SwiftLint only against changed things

**Comment by orta** [comment]
I'd like this also to be able to say only a particular filetype too, I think a space would be fine for this:

```
        "komondor": [
            "pre-push": "swift test",
            "pre-commit": [
                "swift test",
                "swift run swiftformat [edited swift]",
                "swift run swiftlint autocorrect --path [edited swift]",
                "git add .",
            ],
        ],
```

**Comment by cszatma** [comment]
This would be super useful. Is to goal to have similar functionality to lint-staged? Also, would it need to support escaping macros in case someone actually wanted to pass the string `[edited]` to a command?

**Comment by orta** [comment]
Yeah - I think this can be a hybrid of lint-staged and husky 👍 - this syntax could allow most  use cases of lint-staged imagine

I think it's fine to not handle escapes until someone eventually hits that - feels pretty edge-casey
